# Generated by Django 5.1.7 on 2025-03-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CargaFlexitank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_armado', models.DateField()),
                ('fierros_ref', models.TextField()),
                ('litros_cargados', models.FloatField(blank=True, null=True)),
                ('finalizar', models.BooleanField(default=False)),
                ('contenedor', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFlexi.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargaFlexirampla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_armado', models.DateField()),
                ('fierros_ref', models.TextField()),
                ('litros_cargados', models.FloatField(blank=True, null=True)),
                ('finalizar', models.BooleanField(default=False)),
                ('patente_camion', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFlexi.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
