# Generated by Django 5.1.7 on 2025-03-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaflexirampla',
            name='numero_flexi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexirampla',
            name='numero_naviera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexirampla',
            name='sello_flexi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexitank',
            name='numero_flexi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexitank',
            name='numero_naviera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexitank',
            name='sello_flexi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
