# Generated by Django 5.1.7 on 2025-03-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0002_cargaflexirampla_numero_flexi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
