# Generated by Django 5.1.7 on 2025-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaflexirampla',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargaflexitank',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargaflexirampla',
            name='fierros_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cargaflexitank',
            name='fierros_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
