# Generated by Django 5.1.7 on 2025-05-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0006_cargaflexirampla_comentarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('carga_flexirampla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppFlexi.cargaflexirampla')),
                ('carga_flexitank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppFlexi.cargaflexitank')),
            ],
        ),
    ]
