# Generated by Django 5.1.7 on 2025-05-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0007_imagencarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagencarga',
            name='fecha_subida',
        ),
    ]
