# Generated by Django 5.1.7 on 2025-06-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0008_remove_imagencarga_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaflexirampla',
            name='fecha_armado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cargaflexitank',
            name='fecha_armado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagencarga',
            name='carga_flexirampla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppFlexi.cargaflexirampla'),
        ),
        migrations.AlterField(
            model_name='imagencarga',
            name='carga_flexitank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppFlexi.cargaflexitank'),
        ),
        migrations.AlterField(
            model_name='imagencarga',
            name='imagen',
            field=models.ImageField(upload_to='cargas/'),
        ),
    ]
