# Generated by Django 5.1.7 on 2025-06-16 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlexi', '0012_imagencarga_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarga',
            name='carga_flexirampla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppFlexi.cargaflexirampla'),
        ),
        migrations.AlterField(
            model_name='imagencarga',
            name='carga_flexitank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppFlexi.cargaflexitank'),
        ),
    ]
